name: CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: xu-cheng/latex-action@v2
        with:
          root_file: SPL-Rules.tex
      - shell: bash
        env:
          AUTHORIZATION: ${{ secrets.SPL_WORDPRESS_AUTHORIZATION }}
        run: |
          ./.github/scripts/upload_to_wordpress.py spl.robocup.org SPL-Rules.pdf SPL-Rules-master.pdf
